USE customer_db;

-- Preview data
SELECT * FROM customer LIMIT 5;
SELECT COUNT(*) FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, 
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2. Which age group contributes the most to total revenue?
SELECT age_group, 
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

-- Q3. Which locations (states) have the highest total purchase amounts?
SELECT location, 
       SUM(purchase_amount) AS total_purchase_amount
FROM customer
GROUP BY location
ORDER BY total_purchase_amount DESC
LIMIT 1;

-- Q4. What is the average purchase amount per payment method (Credit Card, PayPal, etc.)?
SELECT payment_method, 
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
GROUP BY payment_method
ORDER BY avg_purchase DESC;

-- Q5. Do customers who received a discount tend to spend more or less on average?
SELECT discount_applied, 
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
GROUP BY discount_applied;

-- Q6. Compare the average purchase frequency between subscribed and non-subscribed customers.
SELECT subscription_status, 
       ROUND(AVG(frequency_of_purchases), 2) AS avg_purchase_frequency
FROM customer
GROUP BY subscription_status
ORDER BY avg_purchase_frequency DESC;

-- Q7. Are customers with more than 10 previous purchases also more likely to be subscribers?
SELECT 
    CASE 
        WHEN previous_purchases >= 10 THEN 'More than 10'
        ELSE '10 or fewer'
    END AS purchase_group,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) AS subscribers,
    ROUND(SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS subscription_rate
FROM customer
GROUP BY purchase_group;

-- Q8. Segment customers into New (≤3), Returning (4–10), and Loyal (>10) — show average revenue for each.
SELECT 
    CASE 
        WHEN previous_purchases <= 3 THEN 'New'
        WHEN previous_purchases BETWEEN 4 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS segment,
    ROUND(AVG(purchase_amount), 2) AS avg_amount
FROM customer
GROUP BY segment;

-- Q9. What is the average review rating given by subscribed vs. non-subscribed customers?
SELECT 
    CASE 
        WHEN subscription_status = 'Yes' THEN 'Subscribed'
        ELSE 'Non-Subscribed'
    END AS status,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY status;

-- Q10. Are younger customers (18–30) or older customers (50+) more frequent buyers?
SELECT
    CASE
        WHEN age BETWEEN 18 AND 30 THEN 'Younger Customers'
        ELSE 'Older Customers'
    END AS buyer_group,
    ROUND(AVG(purchase_amount), 2) AS avg_amount
FROM customer
GROUP BY buyer_group;

-- Q11. Which top 5 products have the highest average purchase amount?
SELECT item_purchased, 
       ROUND(AVG(purchase_amount), 2) AS avg_amount
FROM customer
GROUP BY item_purchased
ORDER BY avg_amount DESC
LIMIT 5;

-- Q12. What are the top 3 most purchased products in each category?
SELECT category, 
       item_purchased, 
       total_purchases, 
       rank_
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_
    FROM customer
    GROUP BY category, item_purchased
) ranked
WHERE rank_ <= 3;

-- Q13. Which categories have the highest number of discount purchases?
SELECT category, 
       COUNT(*) AS purchases
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY category
ORDER BY purchases DESC
LIMIT 1;

-- Q14. Compare average review ratings across seasons — which season gets the best-rated products?
SELECT season, 
       avg_rating
FROM (
    SELECT 
        season, 
        ROUND(AVG(review_rating), 2) AS avg_rating,
        RANK() OVER (ORDER BY AVG(review_rating) DESC) AS ranking
    FROM customer
    GROUP BY season
) sub
WHERE ranking = 1;

-- Q15. Which shipping type yields the highest revenue and satisfaction (rating)?
SELECT 
    shipping_type,
    SUM(purchase_amount) AS total_revenue,
    ROUND(AVG(review_rating), 2) AS avg_rating
FROM customer
GROUP BY shipping_type
ORDER BY total_revenue DESC
LIMIT 1;